import { CATEGORY_META } from "./categories";
import { calculateVoiceAiScore } from "./scoring";
import type { Business, BusinessCategory, BusinessStatus } from "./types";

type BusinessSeed = Omit<Business, "voiceAiScore" | "scoreBreakdown">;

function createBusiness(seed: BusinessSeed): Business {
  const { score, breakdown } = calculateVoiceAiScore(seed);

  return {
    ...seed,
    voiceAiScore: score,
    scoreBreakdown: breakdown,
  };
}

const defaultStatus: BusinessStatus = "new";

const categoryUseCases = Object.fromEntries(
  (Object.keys(CATEGORY_META) as BusinessCategory[]).map((category) => [category, CATEGORY_META[category].useCase]),
) as Record<BusinessCategory, string>;

export const mockBusinesses: Business[] = [
  createBusiness({
    id: "hackney-smile-studio",
    name: "Hackney Smile Studio",
    category: "dental",
    address: "Mare Street, Hackney, London",
    borough: "Hackney",
    latitude: 51.545,
    longitude: -0.055,
    phone: "+44 20 7000 1101",
    website: "https://example.com/hackney-smile",
    rating: 4.7,
    reviewCount: 214,
    hasWebsite: true,
    hasOnlineBooking: false,
    hasVisiblePhone: true,
    appointmentBased: true,
    highValueService: true,
    reviewPainSignals: ["phone lines busy", "hard to rearrange appointments"],
    recommendedUseCase: categoryUseCases.dental,
    reasoning: "High-value appointment-based clinic with visible phone dependency and no obvious online booking signal. Public reviews suggest scheduling friction.",
    status: defaultStatus,
  }),
  createBusiness({
    id: "shoreditch-aesthetics-clinic",
    name: "Shoreditch Aesthetics Clinic",
    category: "aesthetics",
    address: "Great Eastern Street, Shoreditch, London",
    borough: "Hackney",
    latitude: 51.5246,
    longitude: -0.0793,
    phone: "+44 20 7000 1102",
    website: "https://example.com/shoreditch-aesthetics",
    rating: 4.8,
    reviewCount: 168,
    hasWebsite: true,
    hasOnlineBooking: false,
    hasVisiblePhone: true,
    appointmentBased: true,
    highValueService: true,
    reviewPainSignals: ["slow replies"],
    recommendedUseCase: categoryUseCases.aesthetics,
    reasoning: "Consultation-led clinic with high-value treatments. Good fit for lead qualification, booking, reminders, and unanswered call capture.",
    status: "needs_review",
  }),
  createBusiness({
    id: "bow-veterinary-care",
    name: "Bow Veterinary Care",
    category: "veterinary",
    address: "Roman Road, Bow, London",
    borough: "Tower Hamlets",
    latitude: 51.5301,
    longitude: -0.0262,
    phone: "+44 20 7000 1103",
    website: "https://example.com/bow-vets",
    rating: 4.5,
    reviewCount: 192,
    hasWebsite: true,
    hasOnlineBooking: false,
    hasVisiblePhone: true,
    appointmentBased: true,
    highValueService: true,
    reviewPainSignals: ["long phone wait", "could not get through"],
    recommendedUseCase: categoryUseCases.veterinary,
    reasoning: "Phone-heavy, appointment-based practice with urgency/triage needs. Reviews indicate possible call-handling pain.",
    status: defaultStatus,
  }),
  createBusiness({
    id: "canary-wharf-dental",
    name: "Canary Wharf Dental Lounge",
    category: "dental",
    address: "Canary Wharf, London",
    borough: "Tower Hamlets",
    latitude: 51.5054,
    longitude: -0.0235,
    phone: "+44 20 7000 1104",
    website: "https://example.com/cw-dental",
    rating: 4.9,
    reviewCount: 340,
    hasWebsite: true,
    hasOnlineBooking: true,
    hasVisiblePhone: true,
    appointmentBased: true,
    highValueService: true,
    reviewPainSignals: [],
    recommendedUseCase: categoryUseCases.dental,
    reasoning: "Strong vertical fit and high review volume, but online booking lowers urgency. Still worth reviewing for after-hours and reminder automation.",
    status: defaultStatus,
  }),
  createBusiness({
    id: "stratford-skin-laser",
    name: "Stratford Skin & Laser",
    category: "aesthetics",
    address: "Stratford High Street, London",
    borough: "Newham",
    latitude: 51.5416,
    longitude: -0.0037,
    phone: "+44 20 7000 1105",
    website: "https://example.com/stratford-skin",
    rating: 4.6,
    reviewCount: 127,
    hasWebsite: true,
    hasOnlineBooking: false,
    hasVisiblePhone: true,
    appointmentBased: true,
    highValueService: true,
    reviewPainSignals: ["waiting for callback"],
    recommendedUseCase: categoryUseCases.aesthetics,
    reasoning: "High-value consultation business in a dense area. Public signals point to callbacks and appointment handling as likely wedge use cases.",
    status: defaultStatus,
  }),
  createBusiness({
    id: "bethnal-green-vets",
    name: "Bethnal Green Vets",
    category: "veterinary",
    address: "Cambridge Heath Road, London",
    borough: "Tower Hamlets",
    latitude: 51.526,
    longitude: -0.0577,
    phone: "+44 20 7000 1106",
    website: "https://example.com/bethnal-vets",
    rating: 4.4,
    reviewCount: 86,
    hasWebsite: true,
    hasOnlineBooking: false,
    hasVisiblePhone: true,
    appointmentBased: true,
    highValueService: true,
    reviewPainSignals: [],
    recommendedUseCase: categoryUseCases.veterinary,
    reasoning: "Good category fit and visible call path. Slightly lower confidence because public review pain signals are not obvious.",
    status: defaultStatus,
  }),
  createBusiness({
    id: "islington-private-dentistry",
    name: "Islington Private Dentistry",
    category: "dental",
    address: "Upper Street, Islington, London",
    borough: "Islington",
    latitude: 51.5412,
    longitude: -0.1024,
    phone: "+44 20 7000 1107",
    website: "https://example.com/islington-dentistry",
    rating: 4.8,
    reviewCount: 258,
    hasWebsite: true,
    hasOnlineBooking: false,
    hasVisiblePhone: true,
    appointmentBased: true,
    highValueService: true,
    reviewPainSignals: ["voicemail", "no answer"],
    recommendedUseCase: categoryUseCases.dental,
    reasoning: "Premium appointment-based clinic with strong call-capture need. Reviews suggest missed-call risk, making this a high-priority prospect.",
    status: "approved_for_contact",
  }),
  createBusiness({
    id: "whitechapel-legal-partners",
    name: "Whitechapel Legal Partners",
    category: "legal",
    address: "Whitechapel Road, London",
    borough: "Tower Hamlets",
    latitude: 51.5195,
    longitude: -0.0598,
    phone: "+44 20 7000 1108",
    website: "https://example.com/whitechapel-legal",
    rating: 4.2,
    reviewCount: 64,
    hasWebsite: true,
    hasOnlineBooking: false,
    hasVisiblePhone: true,
    appointmentBased: true,
    highValueService: true,
    reviewPainSignals: [],
    recommendedUseCase: categoryUseCases.legal,
    reasoning: "Some intake/callback value exists, but legal workflows need careful constraints. Lower priority for this demo.",
    status: defaultStatus,
  }),
  createBusiness({
    id: "dalston-coffee-house",
    name: "Dalston Coffee House",
    category: "restaurant",
    address: "Kingsland High Street, London",
    borough: "Hackney",
    latitude: 51.5467,
    longitude: -0.0753,
    phone: "+44 20 7000 1109",
    website: "https://example.com/dalston-coffee",
    rating: 4.6,
    reviewCount: 512,
    hasWebsite: true,
    hasOnlineBooking: true,
    hasVisiblePhone: true,
    appointmentBased: false,
    highValueService: false,
    reviewPainSignals: [],
    recommendedUseCase: categoryUseCases.restaurant,
    reasoning: "Strong review volume but low appointment complexity and lower Voice AI wedge. Included as a contrast example.",
    status: "not_fit",
  }),
  createBusiness({
    id: "mile-end-pet-clinic",
    name: "Mile End Pet Clinic",
    category: "veterinary",
    address: "Mile End Road, London",
    borough: "Tower Hamlets",
    latitude: 51.5252,
    longitude: -0.0321,
    phone: "+44 20 7000 1110",
    website: undefined,
    rating: 4.1,
    reviewCount: undefined,
    hasWebsite: false,
    hasOnlineBooking: false,
    hasVisiblePhone: true,
    appointmentBased: true,
    highValueService: true,
    reviewPainSignals: [],
    recommendedUseCase: categoryUseCases.veterinary,
    reasoning: "Category fit is strong, but missing website/review context lowers confidence. Worth light review, not top outreach yet.",
    status: defaultStatus,
  }),
  createBusiness({
    id: "city-aesthetic-room",
    name: "City Aesthetic Room",
    category: "aesthetics",
    address: "Liverpool Street, London",
    borough: "City of London",
    latitude: 51.5178,
    longitude: -0.0817,
    phone: "+44 20 7000 1111",
    website: "https://example.com/city-aesthetic",
    rating: 4.9,
    reviewCount: 97,
    hasWebsite: true,
    hasOnlineBooking: true,
    hasVisiblePhone: true,
    appointmentBased: true,
    highValueService: true,
    reviewPainSignals: [],
    recommendedUseCase: categoryUseCases.aesthetics,
    reasoning: "Good fit but existing booking flow reduces immediate pain. Strong candidate for reminders and lead qualification if call volume is high.",
    status: defaultStatus,
  }),
  createBusiness({
    id: "leyton-family-dental",
    name: "Leyton Family Dental",
    category: "dental",
    address: "High Road Leyton, London",
    borough: "Waltham Forest",
    latitude: 51.5586,
    longitude: -0.0062,
    phone: "+44 20 7000 1112",
    website: "https://example.com/leyton-family-dental",
    rating: 4.3,
    reviewCount: 143,
    hasWebsite: true,
    hasOnlineBooking: false,
    hasVisiblePhone: true,
    appointmentBased: true,
    highValueService: true,
    reviewPainSignals: ["couldn't reach reception"],
    recommendedUseCase: categoryUseCases.dental,
    reasoning: "Suburban appointment-based clinic with public signs of reception pressure. Good example of why outer London may produce useful variance.",
    status: defaultStatus,
  }),
];
